# Generated by Django 3.2.3 on 2021-05-14 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PortfolioApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='type',
            field=models.CharField(choices=[('Software', 'Software'), ('Hardware', 'Hardware'), ('Project Management', 'Project Management'), ('Lifestyle', 'Lifestyle')], max_length=50),
        ),
    ]
