# Generated by Django 3.2.3 on 2021-05-14 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PortfolioApp', '0003_auto_20210514_0031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='time',
            field=models.TimeField(),
        ),
    ]
