# Generated by Django 3.2.3 on 2021-05-14 05:44

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('PortfolioApp', '0005_projects'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='projects',
            managers=[
                ('Projects', django.db.models.manager.Manager()),
            ],
        ),
    ]
