# Generated by Django 3.2.3 on 2021-05-14 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PortfolioApp', '0008_alter_project_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='type',
        ),
    ]
