# Generated by Django 3.2.3 on 2021-05-14 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PortfolioApp', '0009_remove_project_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='type',
            field=models.CharField(choices=[('HTML', 'HTML'), ('CSS', 'CSS'), ('Bootstrap', 'Bootstrap'), ('JavaScript', 'Javascript'), ('Python', 'Python'), ('Django', 'Django'), ('JavaScript', 'Javascript'), ('React', 'React'), ('C#', 'C#'), ('C++', 'C++')], default=' ', max_length=25),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='subTitle',
            field=models.CharField(default=' ', max_length=50),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='title',
            field=models.CharField(default=' ', max_length=50),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='type',
            field=models.CharField(choices=[('Software', 'Software'), ('Hardware', 'Hardware'), ('Project Management', 'Project Management'), ('Lifestyle', 'Lifestyle')], default=' ', max_length=25),
        ),
        migrations.AlterField(
            model_name='project',
            name='subTitle',
            field=models.CharField(default=' ', max_length=50),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(default=' ', max_length=50),
        ),
    ]
