# Generated by Django 3.2.3 on 2021-05-14 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PortfolioApp', '0010_auto_20210514_0105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='content',
            field=models.TextField(default=' '),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(default=' ', upload_to=''),
        ),
    ]
