# Generated by Django 3.2.3 on 2021-05-14 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PortfolioApp', '0012_project_toolsused'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='type',
            field=models.CharField(default=' ', max_length=50),
        ),
    ]
