# Generated by Django 3.2.3 on 2021-05-14 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PortfolioApp', '0013_alter_project_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='type',
            field=models.CharField(choices=[('HTML', 'HTML'), ('CSS', 'CSS'), ('Bootstrap', 'Bootstrap'), ('JavaScript', 'Javascript'), ('Python', 'Python'), ('Django', 'Django'), ('JavaScript', 'Javascript'), ('React', 'React'), ('C#', 'C#'), ('C++', 'C++')], default=' ', max_length=25),
        ),
    ]
