# Generated by Django 3.2.3 on 2021-05-14 06:23

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('PortfolioApp', '0014_alter_project_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='type',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('HTML', 'HTML'), ('CSS', 'CSS'), ('Bootstrap', 'Bootstrap'), ('JavaScript', 'Javascript'), ('Python', 'Python'), ('Django', 'Django'), ('JavaScript', 'Javascript'), ('React', 'React'), ('C#', 'C#'), ('C++', 'C++')], max_length=25),
        ),
    ]
