# Generated by Django 3.2.3 on 2021-05-14 06:40

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('PortfolioApp', '0016_rename_type_project_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='toolsUsed',
        ),
        migrations.AddField(
            model_name='project',
            name='IDE',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('VSCode', 'VSCode'), ('Atom', 'Atom'), ('PyCharm', 'PyCharm')], default=' ', max_length=25),
        ),
        migrations.AddField(
            model_name='project',
            name='database',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('MySQL', 'MySQL'), ('MongoDB', 'MongoDB'), ('Oracle', 'Oracle')], default=' ', max_length=25),
        ),
        migrations.AddField(
            model_name='project',
            name='framework',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Bootstrap', 'Bootstrap'), ('Django', 'Django'), ('React', 'React'), ('jQuery', 'jQuery')], default=' ', max_length=25),
        ),
        migrations.AlterField(
            model_name='project',
            name='language',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('HTML', 'HTML'), ('CSS', 'CSS'), ('JavaScript', 'JavaScript'), ('Python', 'Python'), ('Java', 'Java'), ('C#', 'C#'), ('C++', 'C++'), ('Objective-C', 'Objective-C'), ('PHP', 'PHP'), ('Ruby', 'Ruby'), ('SQL', 'SQL')], default=' ', max_length=25),
        ),
    ]
