# Generated by Django 3.2.3 on 2021-05-14 06:54

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('PortfolioApp', '0017_auto_20210514_0140'),
    ]

    operations = [
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.FileField(default=' ', max_length=25, upload_to='')),
                ('email', models.EmailField(default=' ', max_length=254)),
                ('phone', models.IntegerField(default=' ', max_length=10)),
                ('resumePDF', models.FileField(default=' ', upload_to='')),
                ('resumeIMG', models.ImageField(default=' ', upload_to='')),
            ],
            managers=[
                ('Information', django.db.models.manager.Manager()),
            ],
        ),
    ]
