# Generated by Django 3.2.3 on 2021-05-14 06:55

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('PortfolioApp', '0018_information'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Information',
            new_name='Contact',
        ),
        migrations.AlterModelManagers(
            name='contact',
            managers=[
                ('Contacts', django.db.models.manager.Manager()),
            ],
        ),
    ]
