# Generated by Django 3.2.3 on 2021-05-14 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PortfolioApp', '0019_auto_20210514_0155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(default=' ', max_length=25),
        ),
    ]
