# Generated by Django 3.2.3 on 2021-05-14 07:04

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('PortfolioApp', '0022_alter_contact_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='framework',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Bootstrap', 'Bootstrap'), ('Django', 'Django'), ('React', 'React'), ('jQuery', 'jQuery')], default=' ', max_length=25),
        ),
    ]
