# Generated by Django 3.2.3 on 2021-05-15 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PortfolioApp', '0023_alter_project_framework'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='contact',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='project',
            managers=[
            ],
        ),
    ]
