# Generated by Django 3.2.3 on 2021-05-15 16:29

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('PortfolioApp', '0024_auto_20210515_1104'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='contact',
            managers=[
                ('Contacts', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='project',
            managers=[
                ('Projects', django.db.models.manager.Manager()),
            ],
        ),
    ]
