# Generated by Django 3.2.3 on 2021-05-15 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PortfolioApp', '0025_auto_20210515_1129'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='contact',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='project',
            managers=[
            ],
        ),
    ]
