# Generated by Django 3.2.3 on 2021-05-15 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PortfolioApp', '0026_auto_20210515_1130'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='blogpost',
            managers=[
            ],
        ),
    ]
