# Generated by Django 3.2.3 on 2021-05-15 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PortfolioApp', '0027_alter_blogpost_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='outcome',
            field=models.TextField(default=' '),
        ),
        migrations.AddField(
            model_name='project',
            name='purpose',
            field=models.TextField(default=' '),
        ),
        migrations.AddField(
            model_name='project',
            name='reflection',
            field=models.TextField(default=' '),
        ),
    ]
