# Generated by Django 3.2.3 on 2021-05-15 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PortfolioApp', '0028_auto_20210515_1719'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='image',
            new_name='image1',
        ),
        migrations.AddField(
            model_name='project',
            name='image2',
            field=models.ImageField(default=' ', upload_to=''),
        ),
        migrations.AddField(
            model_name='project',
            name='image3',
            field=models.ImageField(default=' ', upload_to=''),
        ),
        migrations.AddField(
            model_name='project',
            name='image4',
            field=models.ImageField(default=' ', upload_to=''),
        ),
    ]
