# Generated by Django 3.2.3 on 2021-05-16 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PortfolioApp', '0030_auto_20210515_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image1',
            field=models.ImageField(upload_to='Portfolio/img/upload/'),
        ),
    ]
