# Generated by Django 3.2.3 on 2021-05-17 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PortfolioApp', '0034_alter_project_image1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image1',
            field=models.ImageField(upload_to='portfolio/static/img/upload/'),
        ),
    ]
