# Generated by Django 3.2.3 on 2021-05-17 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PortfolioApp', '0036_alter_project_image1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image2',
            field=models.ImageField(upload_to='static/img/upload/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image3',
            field=models.ImageField(upload_to='static/img/upload/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image4',
            field=models.ImageField(upload_to='static/img/upload/'),
        ),
    ]
