# Generated by Django 3.2.3 on 2021-05-17 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PortfolioApp', '0042_auto_20210516_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image1',
            field=models.ImageField(upload_to='Portfolio/static/upload/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image2',
            field=models.ImageField(upload_to='Portfolio/static/upload/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image3',
            field=models.ImageField(upload_to='Portfolio/static/upload/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image4',
            field=models.ImageField(upload_to='Portfolio/static/upload/'),
        ),
    ]
